server:
  port: 9191
  servlet:
    context-path: /auth-api

spring:
  datasource:
    url: jdbc:h2:file:./target/data/authdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
    open-in-view: true
  application:
    name: auth-server


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    
management:
  endpoints:
    web:
      exposure:
        include: -*
        exclude: env,beans

logging:
  file: /app/log/auth.log
  level:
    root: WARN
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    org.springframework: INFO
    